#!/usr/bin/env python3
"""Generate the architecture tree and docs from universe.yaml.

Usage:
    python3 architecture/scaffold.py           # regenerate
    python3 architecture/scaffold.py --check   # fail if output is stale

universe.yaml is the source of truth. Everything under architecture/universe/
and architecture/ARCHITECTURE.md is generated and safe to delete.
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent
SPEC = ROOT / "universe.yaml"
TREE_DIR = ROOT / "universe"
DOC = ROOT / "ARCHITECTURE.md"

GENERATED_NOTE = (
    "<!-- Generated by architecture/scaffold.py from architecture/universe.yaml. "
    "Do not edit by hand. -->"
)


def slugify(name: str) -> str:
    """'HTTP/3 Gateway' -> 'http-3-gateway', 'Identity & Security' -> 'identity-and-security'."""
    slug = name.lower().replace("&", " and ")
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    return slug.strip("-")


def children(node: dict) -> list[dict]:
    return node.get("children") or []


def is_leaf(node: dict) -> bool:
    return not children(node)


def walk(node: dict, trail: list[dict] | None = None):
    """Yield (node, ancestors) for every node including the root."""
    trail = trail or []
    yield node, trail
    for child in children(node):
        yield from walk(child, trail + [node])


def count_leaves(node: dict) -> int:
    if is_leaf(node):
        return 1
    return sum(count_leaves(c) for c in children(node))


def clean(text: str) -> str:
    """Collapse YAML folded-scalar whitespace into a single line."""
    return " ".join((text or "").split())


# --------------------------------------------------------------------------- tree


def render_tree(node: dict, prefix: str = "", is_last: bool = True, is_root: bool = True) -> list[str]:
    """ASCII tree in the same shape as the source diagram."""
    if is_root:
        lines = [f"{node['name']}/"]
    else:
        connector = "└── " if is_last else "├── "
        suffix = "/" if children(node) else ""
        lines = [f"{prefix}{connector}{node['name']}{suffix}"]
        prefix += "    " if is_last else "│   "

    kids = children(node)
    for i, child in enumerate(kids):
        last = i == len(kids) - 1
        # Spacer line above each category block, matching the source diagram.
        if children(child):
            lines.append(f"{prefix}│")
        lines.extend(render_tree(child, prefix, last, is_root=False))
    return lines


# --------------------------------------------------------------------------- readmes


def breadcrumb(node: dict, ancestors: list[dict]) -> str:
    parts = [a["name"] for a in ancestors] + [node["name"]]
    return " › ".join(parts)


def readme_for(node: dict, ancestors: list[dict]) -> str:
    lines = [
        GENERATED_NOTE,
        "",
        f"# {node['name']}",
        "",
        f"`{breadcrumb(node, ancestors)}`",
        "",
        clean(node.get("description", "")),
        "",
    ]

    aliases = node.get("aliases")
    if aliases:
        lines += [
            "**Also known as:** " + ", ".join(aliases),
            "",
        ]

    kids = children(node)
    if kids:
        lines += [
            f"## Components ({len(kids)})",
            "",
            "| Component | Purpose |",
            "| --- | --- |",
        ]
        for child in kids:
            link = f"[{child['name']}](./{slugify(child['name'])}/)"
            lines.append(f"| {link} | {clean(child.get('description', ''))} |")
        lines.append("")
    else:
        lines += [
            "## Status",
            "",
            "Not implemented. This directory reserves the component's place in the",
            "tree and is where its implementation, config, and runbook belong.",
            "",
        ]

    if ancestors:
        lines += ["---", "", f"[↑ {ancestors[-1]['name']}](../)", ""]

    return "\n".join(lines)


def write_tree(spec: dict) -> None:
    if TREE_DIR.exists():
        shutil.rmtree(TREE_DIR)

    for node, ancestors in walk(spec):
        path = TREE_DIR.joinpath(*[slugify(a["name"]) for a in ancestors[1:]])
        if ancestors:  # everything below the root gets its own directory
            path = path / slugify(node["name"])
        path.mkdir(parents=True, exist_ok=True)
        (path / "README.md").write_text(readme_for(node, ancestors), encoding="utf-8")


# --------------------------------------------------------------------------- doc


def write_doc(spec: dict) -> None:
    total = sum(1 for _ in walk(spec)) - 1
    leaves = count_leaves(spec)
    tiers = children(spec)

    lines = [
        GENERATED_NOTE,
        "",
        f"# {spec['name']}",
        "",
        clean(spec.get("description", "")),
        "",
        f"**{total} nodes · {leaves} components · {len(tiers)} top-level domains.**",
        "",
        "Source of truth: [`universe.yaml`](./universe.yaml). Regenerate this file and",
        "the [`universe/`](./universe/) tree with `python3 architecture/scaffold.py`.",
        "",
        "## Contents",
        "",
    ]

    for tier in tiers:
        lines.append(f"- [{tier['name']}](#{slugify(tier['name'])}) — {count_leaves(tier)} components")
        for group in children(tier):
            if children(group):
                lines.append(
                    f"  - [{group['name']}](#{slugify(group['name'])}) — {count_leaves(group)} components"
                )
    lines += ["", "## Tree", "", "```", *render_tree(spec), "```", ""]

    for tier in tiers:
        lines += [f"## {tier['name']}", "", clean(tier.get("description", "")), ""]
        groups = [c for c in children(tier) if children(c)]
        if groups:
            for group in groups:
                lines += [f"### {group['name']}", "", clean(group.get("description", "")), ""]
                lines += component_table(group, [tier])
        else:
            lines += component_table(tier, [])

    lines += [
        "## Alias index",
        "",
        "Earlier names, and the component that now owns each one.",
        "",
        "| Former name | Current component |",
        "| --- | --- |",
    ]
    aliases: list[tuple[str, str]] = []
    for node, ancestors in walk(spec):
        for alias in node.get("aliases") or []:
            path = "/".join(slugify(a["name"]) for a in ancestors[1:] + [node])
            aliases.append((alias, f"[{node['name']}](./universe/{path}/)"))
    for alias, target in sorted(aliases, key=lambda pair: pair[0].lower()):
        lines.append(f"| {alias} | {target} |")
    lines.append("")

    DOC.write_text("\n".join(lines), encoding="utf-8")


def component_table(group: dict, trail: list[dict]) -> list[str]:
    """`trail` is the group's ancestor chain below the root, outermost first."""
    path = "/".join(slugify(n["name"]) for n in trail + [group])
    lines = ["| Component | Purpose |", "| --- | --- |"]
    for child in children(group):
        lines.append(
            f"| [{child['name']}](./universe/{path}/{slugify(child['name'])}/) "
            f"| {clean(child.get('description', ''))} |"
        )
    lines.append("")
    return lines


# --------------------------------------------------------------------------- checks


def validate(spec: dict) -> list[str]:
    """Catch the mistakes that silently corrupt the generated tree."""
    errors: list[str] = []
    slugs: dict[str, str] = {}
    names: dict[str, str] = {}

    for node, ancestors in walk(spec):
        where = breadcrumb(node, ancestors)
        if not node.get("name"):
            errors.append(f"{where}: missing name")
            continue
        if not clean(node.get("description", "")):
            errors.append(f"{where}: missing description")

        # Sibling slugs must be unique or directories collide.
        parent = ancestors[-1]["name"] if ancestors else ""
        key = f"{parent}/{slugify(node['name'])}"
        if key in slugs:
            errors.append(f"{where}: slug collides with {slugs[key]}")
        slugs[key] = where

        # Component names must be globally unique so aliases resolve to one node.
        if is_leaf(node):
            lowered = node["name"].lower()
            if lowered in names:
                errors.append(f"{where}: duplicate component name, also at {names[lowered]}")
            names[lowered] = where

    seen: dict[str, str] = {}
    for node, ancestors in walk(spec):
        for alias in node.get("aliases") or []:
            lowered = alias.lower()
            if lowered in seen:
                errors.append(f"alias {alias!r} claimed by both {seen[lowered]} and {node['name']}")
            seen[lowered] = node["name"]
            if lowered in names and names[lowered] != breadcrumb(node, ancestors):
                errors.append(f"alias {alias!r} on {node['name']} shadows a real component")

    return errors


def snapshot() -> dict[str, str]:
    files = {}
    if DOC.exists():
        files[str(DOC)] = DOC.read_text(encoding="utf-8")
    for path in sorted(TREE_DIR.rglob("*.md")):
        files[str(path)] = path.read_text(encoding="utf-8")
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated output is stale")
    args = parser.parse_args()

    spec = yaml.safe_load(SPEC.read_text(encoding="utf-8"))

    errors = validate(spec)
    if errors:
        print(f"{SPEC.name}: {len(errors)} problem(s)", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    before = snapshot() if args.check else None

    write_tree(spec)
    write_doc(spec)

    if args.check:
        after = snapshot()
        if before != after:
            changed = sorted(set(before) ^ set(after)) or sorted(
                path for path in after if before.get(path) != after[path]
            )
            print("Generated output is stale. Run: python3 architecture/scaffold.py", file=sys.stderr)
            for path in changed[:10]:
                print(f"  - {Path(path).relative_to(ROOT.parent)}", file=sys.stderr)
            return 1
        print("Generated output is up to date.")
        return 0

    print(f"Wrote {DOC.relative_to(ROOT.parent)} and {count_leaves(spec)} components under "
          f"{TREE_DIR.relative_to(ROOT.parent)}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
