#!/usr/bin/env python3
"""Generate the architecture tree and docs from universe.yaml.

Usage:
    python3 architecture/scaffold.py           # regenerate
    python3 architecture/scaffold.py --check   # fail if output is stale

universe.yaml is the source of truth. Everything under architecture/universe/
and architecture/ARCHITECTURE.md is generated and safe to delete.
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent
SPEC = ROOT / "universe.yaml"
TREE_DIR = ROOT / "universe"
DOC = ROOT / "ARCHITECTURE.md"

GENERATED_NOTE = (
    "<!-- Generated by architecture/scaffold.py from architecture/universe.yaml. "
    "Do not edit by hand. -->"
)

# Lifecycle a component moves through. Order is meaningful — rollups render in it.
STATUSES = ("planned", "building", "running")
DEFAULT_STATUS = "planned"
DEFAULT_OWNER = "unassigned"
STATUS_BADGE = {"planned": "○ Planned", "building": "◐ Building", "running": "● Running"}
OWNER_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")


def slugify(name: str) -> str:
    """'HTTP/3 Gateway' -> 'http-3-gateway', 'Identity & Security' -> 'identity-and-security'."""
    slug = name.lower().replace("&", " and ")
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    return slug.strip("-")


def mermaid_id(name: str) -> str:
    return "n_" + slugify(name).replace("-", "_")


def mermaid_label(text: str) -> str:
    """Mermaid chokes on bare & " and #; entity-encode them."""
    return text.replace("&", "&amp;").replace('"', "&quot;").replace("#", "&#35;")


def children(node: dict) -> list[dict]:
    return node.get("children") or []


def is_leaf(node: dict) -> bool:
    return not children(node)


def walk(node: dict, trail: list[dict] | None = None):
    """Yield (node, ancestors) for every node including the root."""
    trail = trail or []
    yield node, trail
    for child in children(node):
        yield from walk(child, trail + [node])


def leaves(node: dict):
    for candidate, _ in walk(node):
        if is_leaf(candidate):
            yield candidate


def count_leaves(node: dict) -> int:
    return sum(1 for _ in leaves(node))


def clean(text: str) -> str:
    """Collapse YAML folded-scalar whitespace into a single line."""
    return " ".join((text or "").split())


def inherited(node: dict, ancestors: list[dict], key: str, default: str) -> str:
    """Nearest explicit value walking up from the node, else the default.

    Lets a tier set `owner` once instead of repeating it on all 20 components.
    """
    for candidate in [node, *reversed(ancestors)]:
        if candidate.get(key):
            return candidate[key]
    return default


def status_of(node: dict, ancestors: list[dict]) -> str:
    return inherited(node, ancestors, "status", DEFAULT_STATUS)


def owner_of(node: dict, ancestors: list[dict]) -> str:
    return inherited(node, ancestors, "owner", DEFAULT_OWNER)


def build_index(spec: dict) -> dict[str, tuple[dict, list[dict]]]:
    """Lowercased component name AND alias -> (node, ancestors).

    Aliases resolve too, so a `depends_on` written against an old name still
    points at the component that superseded it.
    """
    index: dict[str, tuple[dict, list[dict]]] = {}
    for node, ancestors in walk(spec):
        if not node.get("name"):
            continue
        index[node["name"].lower()] = (node, ancestors)
        for alias in node.get("aliases") or []:
            index.setdefault(alias.lower(), (node, ancestors))
    return index


def depends_on(node: dict) -> list[str]:
    return node.get("depends_on") or []


def dependency_edges(spec: dict) -> list[tuple[str, str]]:
    """(source name, resolved target name) for every declared dependency."""
    index = build_index(spec)
    edges = []
    for node, _ in walk(spec):
        for target in depends_on(node):
            found = index.get(target.lower())
            if found:
                edges.append((node["name"], found[0]["name"]))
    return edges


def find_cycles(spec: dict) -> list[list[str]]:
    """Every dependency cycle, as name paths. A cycle means nothing can boot."""
    index = build_index(spec)
    graph: dict[str, list[str]] = {}
    for node, _ in walk(spec):
        if not node.get("name"):
            continue
        resolved = []
        for target in depends_on(node):
            found = index.get(target.lower())
            if found:
                resolved.append(found[0]["name"])
        graph[node["name"]] = resolved

    cycles: list[list[str]] = []
    seen_cycles: set[tuple[str, ...]] = set()
    WHITE, GREY, BLACK = 0, 1, 2
    colour = {name: WHITE for name in graph}

    def visit(name: str, path: list[str]) -> None:
        colour[name] = GREY
        path.append(name)
        for nxt in graph.get(name, []):
            if colour.get(nxt) == GREY:
                cycle = path[path.index(nxt):] + [nxt]
                # Normalise rotation so one cycle is not reported many times.
                core = tuple(cycle[:-1])
                spin = min(range(len(core)), key=lambda i: core[i:] + core[:i])
                key = core[spin:] + core[:spin]
                if key not in seen_cycles:
                    seen_cycles.add(key)
                    cycles.append(list(key) + [key[0]])
            elif colour.get(nxt) == WHITE:
                visit(nxt, path)
        path.pop()
        colour[name] = BLACK

    for name in graph:
        if colour[name] == WHITE:
            visit(name, [])
    return cycles


def dependents_map(spec: dict) -> dict[str, list[str]]:
    """Reverse edges: component -> everything that depends on it."""
    reverse: dict[str, list[str]] = {}
    for source, target in dependency_edges(spec):
        reverse.setdefault(target, []).append(source)
    return {k: sorted(set(v)) for k, v in reverse.items()}


def status_rollup(node: dict, ancestors: list[dict]) -> dict[str, int]:
    """Component counts by status for everything beneath `node`."""
    counts = {s: 0 for s in STATUSES}
    for candidate, trail in walk(node):
        if is_leaf(candidate):
            counts[status_of(candidate, ancestors + trail)] += 1
    return counts


def rollup_text(counts: dict[str, int]) -> str:
    parts = [f"{n} {name}" for name, n in counts.items() if n]
    return ", ".join(parts) or "no components"


# --------------------------------------------------------------------------- tree


def render_tree(node: dict, prefix: str = "", is_last: bool = True, is_root: bool = True) -> list[str]:
    """ASCII tree in the same shape as the source diagram."""
    if is_root:
        lines = [f"{node['name']}/"]
    else:
        connector = "└── " if is_last else "├── "
        suffix = "/" if children(node) else ""
        lines = [f"{prefix}{connector}{node['name']}{suffix}"]
        prefix += "    " if is_last else "│   "

    kids = children(node)
    for i, child in enumerate(kids):
        last = i == len(kids) - 1
        # Spacer line above each category block, matching the source diagram.
        if children(child):
            lines.append(f"{prefix}│")
        lines.extend(render_tree(child, prefix, last, is_root=False))
    return lines


def render_diagram(spec: dict) -> list[str]:
    """Tier-level Mermaid flowchart.

    Deliberately stops at tiers — all 157 components on one canvas is a hairball,
    and the ASCII tree already covers full depth.
    """
    lines = ["```mermaid", "flowchart TD", f'    {mermaid_id(spec["name"])}(["{spec["name"]}"])']
    for domain in children(spec):
        d_id = mermaid_id(domain["name"])
        label = f'{mermaid_label(domain["name"])}<br/><small>{count_leaves(domain)} components</small>'
        lines.append(f'    {mermaid_id(spec["name"])} --> {d_id}["{label}"]')
        # Only descend into real tiers. A domain whose children are components
        # (Global Infrastructure) stops here rather than spilling 15 leaf nodes.
        for tier in [c for c in children(domain) if children(c)]:
            t_id = mermaid_id(tier["name"])
            t_label = f'{mermaid_label(tier["name"])}<br/><small>{count_leaves(tier)}</small>'
            lines.append(f'    {d_id} --> {t_id}["{t_label}"]')
    lines += ["```", ""]
    return lines


# --------------------------------------------------------------------------- readmes


def breadcrumb(node: dict, ancestors: list[dict]) -> str:
    parts = [a["name"] for a in ancestors] + [node["name"]]
    return " › ".join(parts)


def path_to(target: dict, target_ancestors: list[dict], from_ancestors: list[dict]) -> str:
    """Relative link from one node's directory to another's."""
    up = "../" * (len(from_ancestors) + 1)
    down = "/".join(slugify(n["name"]) for n in target_ancestors[1:] + [target])
    return f"{up}universe/{down}/"


def readme_for(node: dict, ancestors: list[dict], spec: dict | None = None) -> str:
    lines = [
        GENERATED_NOTE,
        "",
        f"# {node['name']}",
        "",
        f"`{breadcrumb(node, ancestors)}`",
        "",
        clean(node.get("description", "")),
        "",
    ]

    aliases = node.get("aliases")
    if aliases:
        lines += ["**Also known as:** " + ", ".join(aliases), ""]

    kids = children(node)
    if kids:
        counts = status_rollup(node, ancestors)
        lines += [
            "| | |",
            "| --- | --- |",
            f"| **Owner** | `{owner_of(node, ancestors)}` |",
            f"| **Components** | {len(kids)} ({rollup_text(counts)}) |",
            "",
            "## Components",
            "",
            "| Component | Status | Purpose |",
            "| --- | --- | --- |",
        ]
        for child in kids:
            link = f"[{child['name']}](./{slugify(child['name'])}/)"
            badge = STATUS_BADGE[status_of(child, ancestors + [node])]
            lines.append(f"| {link} | {badge} | {clean(child.get('description', ''))} |")
        lines.append("")
    else:
        lines += [
            "| | |",
            "| --- | --- |",
            f"| **Status** | {STATUS_BADGE[status_of(node, ancestors)]} |",
            f"| **Owner** | `{owner_of(node, ancestors)}` |",
            "",
        ]

        if spec is not None:
            index = build_index(spec)
            reverse = dependents_map(spec)

            def links(names: list[str]) -> str:
                out = []
                for name in names:
                    found = index.get(name.lower())
                    if found:
                        out.append(f"[{found[0]['name']}]({path_to(found[0], found[1], ancestors)})")
                return ", ".join(out)

            upstream = depends_on(node)
            downstream = reverse.get(node["name"], [])
            lines += [
                "## Dependencies",
                "",
                f"**Depends on:** {links(upstream) if upstream else '_nothing — this is a foundation._'}",
                "",
                f"**Depended on by:** {links(downstream) if downstream else '_nothing yet._'}",
                "",
            ]

        lines += [
            "This directory holds the component's implementation, config, and runbook.",
            "Change its status in `architecture/universe.yaml` and regenerate.",
            "",
        ]

    if ancestors:
        lines += ["---", "", f"[↑ {ancestors[-1]['name']}](../)", ""]

    return "\n".join(lines)


def write_tree(spec: dict) -> None:
    if TREE_DIR.exists():
        shutil.rmtree(TREE_DIR)

    for node, ancestors in walk(spec):
        path = TREE_DIR.joinpath(*[slugify(a["name"]) for a in ancestors[1:]])
        if ancestors:  # everything below the root gets its own directory
            path = path / slugify(node["name"])
        path.mkdir(parents=True, exist_ok=True)
        (path / "README.md").write_text(readme_for(node, ancestors, spec), encoding="utf-8")


# --------------------------------------------------------------------------- doc


def write_doc(spec: dict) -> None:
    total = sum(1 for _ in walk(spec)) - 1
    total_leaves = count_leaves(spec)
    domains = children(spec)
    counts = status_rollup(spec, [])

    lines = [
        GENERATED_NOTE,
        "",
        f"# {spec['name']}",
        "",
        clean(spec.get("description", "")),
        "",
        f"**{total} nodes · {total_leaves} components · {len(domains)} top-level domains.**",
        "",
        "Source of truth: [`universe.yaml`](./universe.yaml). Regenerate this file and",
        "the [`universe/`](./universe/) tree with `python3 architecture/scaffold.py`.",
        "",
        "## Status",
        "",
        "| Status | Components | Share |",
        "| --- | --- | --- |",
    ]
    for status in STATUSES:
        n = counts[status]
        share = f"{100 * n / total_leaves:.0f}%" if total_leaves else "—"
        lines.append(f"| {STATUS_BADGE[status]} | {n} | {share} |")
    lines += [
        "",
        "A component having a directory does not mean it is running — this tree is a",
        "map, not an inventory.",
        "",
        "## Map",
        "",
        "Tier level only; the [tree](#tree) below goes to full depth.",
        "",
    ]
    lines += render_diagram(spec)

    lines += ["## Contents", ""]
    for domain in domains:
        lines.append(
            f"- [{domain['name']}](#{slugify(domain['name'])}) — {count_leaves(domain)} components"
        )
        for tier in children(domain):
            if children(tier):
                lines.append(
                    f"  - [{tier['name']}](#{slugify(tier['name'])}) — {count_leaves(tier)} components"
                )
    lines += ["", "## Tree", "", "```", *render_tree(spec), "```", ""]

    for domain in domains:
        lines += [f"## {domain['name']}", "", clean(domain.get("description", "")), ""]
        tiers = [c for c in children(domain) if children(c)]
        if tiers:
            for tier in tiers:
                lines += [
                    f"### {tier['name']}",
                    "",
                    clean(tier.get("description", "")),
                    "",
                    f"**Owner:** `{owner_of(tier, [spec, domain])}` · "
                    f"**{count_leaves(tier)} components** "
                    f"({rollup_text(status_rollup(tier, [spec, domain]))})",
                    "",
                ]
                lines += component_table(tier, [domain], [spec, domain])
        else:
            lines += [
                f"**Owner:** `{owner_of(domain, [spec])}` · "
                f"**{count_leaves(domain)} components** "
                f"({rollup_text(status_rollup(domain, [spec]))})",
                "",
            ]
            lines += component_table(domain, [], [spec])

    lines += dependency_section(spec)

    lines += [
        "## Ownership",
        "",
        "Owners are inherited down the tree — a tier's owner applies to every",
        "component under it unless that component overrides it.",
        "",
        "| Owner | Components |",
        "| --- | --- |",
    ]
    owners: dict[str, int] = {}
    for node, ancestors in walk(spec):
        if is_leaf(node):
            owners[owner_of(node, ancestors)] = owners.get(owner_of(node, ancestors), 0) + 1
    for owner, n in sorted(owners.items(), key=lambda kv: (-kv[1], kv[0])):
        lines.append(f"| `{owner}` | {n} |")

    lines += [
        "",
        "## Alias index",
        "",
        "Earlier names, and the component that now owns each one.",
        "",
        "| Former name | Current component |",
        "| --- | --- |",
    ]
    aliases: list[tuple[str, str]] = []
    for node, ancestors in walk(spec):
        for alias in node.get("aliases") or []:
            path = "/".join(slugify(a["name"]) for a in ancestors[1:] + [node])
            aliases.append((alias, f"[{node['name']}](./universe/{path}/)"))
    for alias, target in sorted(aliases, key=lambda pair: pair[0].lower()):
        lines.append(f"| {alias} | {target} |")
    lines.append("")

    DOC.write_text("\n".join(lines), encoding="utf-8")


def tier_of(ancestors: list[dict]) -> str:
    """The tier (or domain, for a domain whose children are components) a node sits in."""
    return ancestors[-1]["name"] if len(ancestors) > 1 else ancestors[-1]["name"]


def dependency_section(spec: dict) -> list[str]:
    index = build_index(spec)
    edges = dependency_edges(spec)
    reverse = dependents_map(spec)
    total = count_leaves(spec)
    with_deps = sum(1 for n in leaves(spec) if depends_on(n))
    foundations = [n["name"] for n in leaves(spec) if not depends_on(n)]

    lines = [
        "## Dependencies",
        "",
        f"{len(edges)} edges across {total} components. {with_deps} declare a dependency; "
        f"{len(foundations)} are foundations that depend on nothing.",
        "",
        "The generator rejects a cycle outright — a dependency loop means nothing in it",
        "can start.",
        "",
        "### Most depended on",
        "",
        "The load-bearing components. An outage here fans out furthest.",
        "",
        "| Component | Depended on by |",
        "| --- | --- |",
    ]
    ranked = sorted(reverse.items(), key=lambda kv: (-len(kv[1]), kv[0]))[:12]
    for name, dependents in ranked:
        node, ancestors = index[name.lower()]
        path = "/".join(slugify(a["name"]) for a in ancestors[1:] + [node])
        lines.append(f"| [{name}](./universe/{path}/) | {len(dependents)} |")

    # Aggregate component edges up to tier level; the per-component graph is a hairball.
    pair_counts: dict[tuple[str, str], int] = {}
    for source, target in edges:
        s_tier = tier_of(index[source.lower()][1])
        t_tier = tier_of(index[target.lower()][1])
        if s_tier != t_tier:
            pair_counts[(s_tier, t_tier)] = pair_counts.get((s_tier, t_tier), 0) + 1

    tier_names = sorted({t for pair in pair_counts for t in pair})
    lines += [
        "",
        "### Coupling between tiers",
        "",
        "Cross-tier edges only. Edges inside a tier are omitted, as is the per-component",
        "graph — 157 nodes on one canvas is unreadable. Each component's own page lists",
        "its exact upstreams and downstreams.",
        "",
        "Rows depend on columns.",
        "",
        "| depends on → | " + " | ".join(abbreviate(t) for t in tier_names) + " |",
        "| --- |" + " ---:|" * len(tier_names),
    ]
    for source in tier_names:
        cells = [str(pair_counts.get((source, target), "") or "·") for target in tier_names]
        lines.append(f"| **{source}** | " + " | ".join(cells) + " |")

    threshold = 3
    strong = {pair: n for pair, n in pair_counts.items() if n >= threshold}
    lines += [
        "",
        f"Only the strong links ({threshold}+ edges), so the shape stays legible:",
        "",
        "```mermaid",
        "flowchart LR",
    ]
    for tier in sorted({t for pair in strong for t in pair}):
        lines.append(f'    {mermaid_id(tier)}["{mermaid_label(tier)}"]')
    for (s_tier, t_tier), n in sorted(strong.items(), key=lambda kv: (-kv[1], kv[0])):
        lines.append(f"    {mermaid_id(s_tier)} -->|{n}| {mermaid_id(t_tier)}")
    lines += ["```", ""]
    return lines


def abbreviate(tier: str) -> str:
    """Column headers for the coupling matrix; full names make it far too wide."""
    words = tier.replace("&", "").split()
    return "".join(w[0] for w in words if w).upper()


def component_table(group: dict, trail: list[dict], ancestors: list[dict]) -> list[str]:
    """`trail` is the group's ancestor chain below the root, outermost first."""
    path = "/".join(slugify(n["name"]) for n in trail + [group])
    lines = ["| Component | Status | Purpose |", "| --- | --- | --- |"]
    for child in children(group):
        badge = STATUS_BADGE[status_of(child, ancestors + [group])]
        lines.append(
            f"| [{child['name']}](./universe/{path}/{slugify(child['name'])}/) "
            f"| {badge} | {clean(child.get('description', ''))} |"
        )
    lines.append("")
    return lines


# --------------------------------------------------------------------------- checks


def validate(spec: dict) -> list[str]:
    """Catch the mistakes that silently corrupt the generated tree."""
    errors: list[str] = []
    slugs: dict[str, str] = {}
    names: dict[str, str] = {}

    for node, ancestors in walk(spec):
        where = breadcrumb(node, ancestors)
        if not node.get("name"):
            errors.append(f"{where}: missing name")
            continue
        if not clean(node.get("description", "")):
            errors.append(f"{where}: missing description")

        status = node.get("status")
        if status is not None and status not in STATUSES:
            errors.append(f"{where}: status {status!r} not one of {', '.join(STATUSES)}")

        owner = node.get("owner")
        if owner is not None and not OWNER_RE.match(str(owner)):
            errors.append(f"{where}: owner {owner!r} is not a lowercase team slug")

        # Sibling slugs must be unique or directories collide.
        parent = ancestors[-1]["name"] if ancestors else ""
        key = f"{parent}/{slugify(node['name'])}"
        if key in slugs:
            errors.append(f"{where}: slug collides with {slugs[key]}")
        slugs[key] = where

        # Component names must be globally unique so aliases resolve to one node.
        if is_leaf(node):
            lowered = node["name"].lower()
            if lowered in names:
                errors.append(f"{where}: duplicate component name, also at {names[lowered]}")
            names[lowered] = where

    index = build_index(spec)
    for node, ancestors in walk(spec):
        where = breadcrumb(node, ancestors)
        declared = depends_on(node)
        if declared and not is_leaf(node):
            errors.append(f"{where}: depends_on belongs on components, not groups")
        for target in declared:
            if target.lower() == str(node.get("name", "")).lower():
                errors.append(f"{where}: depends on itself")
            elif target.lower() not in index:
                errors.append(f"{where}: depends on unknown component {target!r}")
            elif not is_leaf(index[target.lower()][0]):
                errors.append(f"{where}: depends on {target!r}, which is a group not a component")
        if len(declared) != len(set(t.lower() for t in declared)):
            errors.append(f"{where}: duplicate entries in depends_on")

    for cycle in find_cycles(spec):
        errors.append("dependency cycle: " + " -> ".join(cycle))

    seen: dict[str, str] = {}
    for node, ancestors in walk(spec):
        for alias in node.get("aliases") or []:
            lowered = alias.lower()
            if lowered in seen:
                errors.append(f"alias {alias!r} claimed by both {seen[lowered]} and {node['name']}")
            seen[lowered] = node["name"]
            if lowered in names and names[lowered] != breadcrumb(node, ancestors):
                errors.append(f"alias {alias!r} on {node['name']} shadows a real component")

    return errors


def snapshot() -> dict[str, str]:
    files = {}
    if DOC.exists():
        files[str(DOC)] = DOC.read_text(encoding="utf-8")
    for path in sorted(TREE_DIR.rglob("*.md")):
        files[str(path)] = path.read_text(encoding="utf-8")
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated output is stale")
    args = parser.parse_args()

    spec = yaml.safe_load(SPEC.read_text(encoding="utf-8"))

    errors = validate(spec)
    if errors:
        print(f"{SPEC.name}: {len(errors)} problem(s)", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    before = snapshot() if args.check else None

    write_tree(spec)
    write_doc(spec)

    if args.check:
        after = snapshot()
        if before != after:
            changed = sorted(set(before) ^ set(after)) or sorted(
                path for path in after if before.get(path) != after[path]
            )
            print("Generated output is stale. Run: python3 architecture/scaffold.py", file=sys.stderr)
            for path in changed[:10]:
                print(f"  - {Path(path).relative_to(ROOT.parent)}", file=sys.stderr)
            return 1
        print("Generated output is up to date.")
        return 0

    print(f"Wrote {DOC.relative_to(ROOT.parent)} and {count_leaves(spec)} components under "
          f"{TREE_DIR.relative_to(ROOT.parent)}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
